services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080" # Changed from 80 to 5000 because port 80 is already in use on the server.
    env_file:
      - production.env
    depends_on:
      - mongo
    networks:
      - fiit-network
    restart: always

  mongo:
    image: mongo:latest
    # ports:
    #   - "27017:27017" # Removed to avoid conflict with host and for security. API still connects internally.
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodbfolder # Make sure this matches the connection string in production.env
    volumes:
      - mongo_data:/data/db
    networks:
      - fiit-network
    restart: always

networks:
  fiit-network:
    driver: bridge

volumes:
  mongo_data:
